# **********************
# ** DEVELOPMENT ONLY **
# **********************
version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: "--innodb_use_native_aio=0"
    volumes:
      - /var/lib/mysql/welllian-db:/var/lib/mysql
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: welllian-local
  adminer:
    image: adminer
    ports:
      - "8306:8080"
    depends_on:
      - db
    links:
      - db
